### ISSUE TITLE
General presentation and link issue on https://www.sky.com/toolkit site

### ISSUE THREAD

**Issue by bk10aao** [sky-uk/toolkit#171] opened 2017-02-21 11:39 UTC
**[General site issue](https://www.sky.com/toolkit) not toolkit related.**

The footer of the page isn't fixed and displays background underneath.
The link on page https://www.sky.com/toolkit/resources to Sketch Resources opens email to dan.bryson@sky.uk and not a 'Library of Sky design patterns'. 

## Expected Behavior
Unclear. Missed intended functionality from designers?

**Comment by joebell93** [comment] 2017-02-21 11:42
Cheers for taking the time to raise this

Closing as it's a duplicate of https://github.com/sky-uk/toolkit/issues/142

**Closed by joebell93** 2017-02-21 11:42 UTC
