### ISSUE TITLE
Sass MQ not configured correctly

### ISSUE THREAD

**Issue by joebell93** [sky-uk/toolkit#203] opened 2017-04-25 14:48 UTC
Spotted by @aaronthomas 

## Expected Behavior
`em` breakpoints are calculated via the correct body font size.

## Current Behavior
`em` breakpoints are calculated via the default sass-mq settings (`16px`).

## Attempted Fixes
Add `$mq-base-font-size: $global-font-size;` to `settings/breakpoints`.

## Context
Breakpoints are not outputting to the expected `em` values

**Comment by csswizardry** [comment] 2017-04-27 16:12
:oops:

**Comment by csswizardry** [comment] 2017-05-02 10:18
These are the unique media queries that will be changed when we move from the preset 16px base font-size to the Sky-defined 18px:

```diff
> @media (min-width: 21em) {
< @media (min-width: 26.25em) {
> @media (min-width: 37em) {
< @media (min-width: 46.25em) {
> @media (min-width: 49em) {
< @media (min-width: 61.25em) {
> @media (min-width: 65em) {
< @media (min-width: 81.25em) {
```

**Comment by MrDinsdale** [comment] 2017-06-08 14:06
Hey, just done some digging into some unusual breakpoint behaviour and this change seems to be the cause.

Essentially the browser ignores `font-size` and always basses it off of `16px`. This means using:

```
html {
  font-size: 32px;

  @include mq($from: 10em) {
    // ...
  }
}
```

The above would not fire at `320px` but instead at `160px` because the browser ignores the `font-size: 32px`.

We should roll back this change and keep at the default value. This is why it hasn't broken already.

**Comment by joebell93** [comment] 2017-06-08 20:54
Have you tried this in the 2.0 branch though @mrdinsdale? I've not seen any of this behaviour you've highlighted in there

+ don't forget we set the font-size of the html in generic/page to be the same value as the sass variable

**Comment by StefanMcCready** [comment] 2017-06-08 21:10
@joebell93 I have been running the v2 branches in Mobile Sales and that is where we are seeing this issue

**Comment by MrDinsdale** [comment] 2017-06-09 09:58
I haven't been able to run against Sky Pages due to quite a lot of build failures however I have made a codepen to illustrate and created a vanilla toolbelt app using v2 to test this is not a problem with Mobile site.

This was taken on a Toolbelt app upgraded to v2, no config changed:
<img width="1866" alt="screen shot 2017-06-09 at 10 54 07" src="https://user-images.githubusercontent.com/2472440/26970630-ffa041aa-4d01-11e7-9e0f-9cc39759ea97.png">

Here the medium breakpoint kicks in around 660px (assigned to 740px in `$mq-breakpoints`). You can see the em value calculated by sass-mq is `41.11111em` (740px/18px) so sass-mq is working however that base font-size of 18px is ignored.

To prove this  `41.11111em` based on the 16px base font-size is 657.777... which is spot on with what we see here.

**Comment by MrDinsdale** [comment] 2017-06-09 12:18
It's also worth noting that if the value set for `$mq-base-font-size` was used with media queries we would have seen massive issues when setting `20px` on `html` and `body` elements.

**Comment by MrDinsdale** [comment] 2017-06-09 14:14
Managed to get V2 Sky Pages up and running and it does appear to be broken.

With V2 and the mq font size change:
<img width="955" alt="screen shot 2017-06-09 at 15 07 42" src="https://user-images.githubusercontent.com/2472440/26979078-843f20a2-4d25-11e7-9377-984261e266b9.png">

This should break to a three column layout at 1024px but its actually breaking at around 911px.

**Closed** 2017-06-12 14:07 UTC
Labels: bug, toolkit-core
