### ISSUE TITLE
Layout Docs

### ISSUE THREAD

**Issue by claredevine** [sky-uk/toolkit#340] opened 2017-12-13 12:11 UTC
## Context
No current docs on the repo for `Layout`.

**Comment by joebell93** [comment] 2017-12-13 12:59
@claredevine cheers for raising! I'm closing this because it's a dupe of https://github.com/sky-uk/toolkit/issues/267, but also because the docs exist on the Supercell repo

**Closed by joebell93** 2017-12-13 12:59 UTC
